## let's learn the concepts of numpy  

In [2]:
import numpy as np

In [8]:
list1 = [2, 4, 6, 8, 10]
n_arr=np.array(list1) # converting list to narray
print(n_arr)
print(n_arr + 1)  #element wise operation

[ 2  4  6  8 10]
[ 3  5  7  9 11]


In [31]:
list2 = [[9, 0, 4, 6], 
         [4 ,6, 1, 1]]
arr2 = np.array(list2)
arr2

array([[9, 0, 4, 6],
       [4, 6, 1, 1]])

In [15]:
arr3 = arr2.astype('bool')
print(arr3)
arr4=np.array(arr3,dtype='float')
print(arr4)
arr4.tolist()
print(arr4) # converitng arr back to list 

[[ True False  True  True]
 [ True  True  True  True]]
[[1. 0. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
print("size",arr3.size)
print("shape",arr3.shape)
print("data type: ",arr3.dtype)
print("num of dimension: ",arr3.ndim)
print("max: ",arr3.max())
print("min: ",arr3.min())
print("mean: ",arr3.mean())
print("median: ",np.median(arr3))
print("sum: ",arr3.sum())
print("average: ",np.average(arr3))
print("var: ",arr3.var())
arr3 = arr3.reshape(4,2)
print("shape now:",arr3.shape)



size 8
shape (2, 4)
data type:  bool
num of dimension:  2
max:  True
min:  False
mean:  0.875
median:  1.0
sum:  7
average:  0.875
var:  0.109375
shape now: (4, 2)


In [27]:
print(np.arange(2,10))
print(np.arange(10,0,-1))

[2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]


In [35]:
arr2=arr4
print(arr2.shape)
arr2.flatten()

(2, 4)


array([1., 0., 1., 1., 1., 1., 1., 1.])

In [39]:
arr5= np.linspace(start=1,stop=10,num=3)
arr5
print(np.zeros([10,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [43]:

arr = [[1, 4, 5, 2 ,2, 5], 
       [4, 4, 1, 7, 4, 5]]
unique_values,count=np.unique(arr,return_counts=True)
print(unique_values)
print(count)

[1 2 4 5 7]
[2 2 4 3 1]
